name: animu_web
description: Animu Website & Dashboard
version: 0.0.1

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_components: ^0.13.0+1
  angular_router: ^2.0.0-alpha

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.5.1
  build_test: ^0.10.0
  build_web_compilers: ^2.4.0
  test: ^1.6.0
  sass_builder: ^2.1.3
