################################# Default configuration ###################
# provide your domain here
baseURL = "https://animu.aldovia.moe/"
# theme
theme = "dot"
# site title
title = "Animu | Help Center"
# desable language
disableLanguages = []

############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#b721ff"
secondary_color = "#121212"
text_color = "#ffffff99"
text_color_dark = "#ffffffDE"
white_color = "#ffffff"

# font family
font_family = "Open Sans" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "https://formspree.io/mjvwardw" # contact form works with : https://formspree.io

############################## social links ##############################
# [[params.social]]
# icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
# link = "#"

# [[params.social]]
# icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
# link = "real_aldovia"
  
# [[params.social]]
# icon = "ti-vimeo-alt" # themify icon pack : https://themify.me/themify-icons
# link = "#"
  
# [[params.social]]
# icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
# link = "#"


################################# navigation ################################
[[menu.main]]
name = "← Back to Website"
url = "https://animu.aldovia.moe"
weight = 1

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = "Copyright © 2020 [Animu](https://animu.aldovia.moe/). All rights reserved"

# banner
[Languages.en.params.banner]
title = "Animu Help Center"
description = "Get to know more about Animu or get in touch with us ;)"
bg_image = "images/banner.jpg"
placeholder = "Have a question? Just ask here or enter terms"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
description = "Contact us and we'll try our best to help you out."
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact"